### ISSUE TITLE
“IndexOutOfBoundsException”,Why does this exception occur？

### ISSUE THREAD

**Issue by shubingo-android** [Giphy/giphy-android-sdk#130]
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 34
       at java.util.Collections$EmptyList.get(Collections.java:4502)
       at androidx.recyclerview.widget.ListAdapter.getItem(ListAdapter.java:150)
       at com.giphy.sdk.ui.universallist.SmartGridAdapter.access$getItem(SmartGridAdapter.java:21)
       at com.giphy.sdk.ui.universallist.SmartGridAdapter$onBindViewHolder$1.onClick(SmartGridAdapter.java:59)
       at android.view.View.performClick(View.java:6733)
       at android.view.View.performClickInternal(View.java:6691)
       at android.view.View.access$3400(View.java:802)
       at android.view.View$PerformClick.run(View.java:26499)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7191)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by ALexanderLonsky** [comment]
@shubingo-android could you please provide steps to reproduce?

**Comment by shubingo-android** [comment]
> @shubingo-android could you please provide steps to reproduce?

this crash is from firebase，I don’t know the specific steps to reproduce，

**Comment by ALexanderLonsky** [comment]
duplicated: #133
