### ISSUE TITLE
Exoplayer version incompatibility causing crashes on clips

### ISSUE THREAD

**Issue by ow-ro** [Giphy/giphy-android-sdk#170]
We are using Exoplayer (v2.14.2) in our app and have recently started using the Giphy SDK (2.1.12), which uses Exoplayer 2.13.3. 

Up until now we have only been using gifs and haven't had any issues. We want to start using clips as well, however tapping on any causes a crash (stack trace below), seemingly due to an Exoplayer version incompatibility, possibly due to [these](https://github.com/google/ExoPlayer/commit/4fc4ddbc6a9ccdcbd4e591c3cfe48f2de45fbd7a) changes in 2.14

Can Giphy's Exoplayer dependency be updated to a more recent release?

Thanks

`2022-01-04 17:17:45.666 26207-26207/com.wemesh.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wemesh.android, PID: 26207
    java.lang.NoSuchMethodError: No virtual method getAudioComponent()Lcom/google/android/exoplayer2/Player$AudioComponent; in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/com.wemesh.android-aAy4TmP0YpGcFcsJoHCTfg==/base.apk!classes2.dex)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.getVolume(GPHVideoPlayer.kt:147)
        at com.giphy.sdk.ui.views.GPHVideoControls.updateSoundModeIcon(GPHVideoControls.kt:247)
        at com.giphy.sdk.ui.views.GPHVideoControls.prepare(GPHVideoControls.kt:85)
        at com.giphy.sdk.ui.views.GPHVideoPlayerView.prepare(GPHVideoPlayerView.kt:132)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.loadMedia(GPHVideoPlayer.kt:238)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.loadMedia$default(GPHVideoPlayer.kt:189)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.showVideoAttributionScreen(GiphyDialogFragment.kt:1404)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onGifSelected(GiphyDialogFragment.kt:1137)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.access$onGifSelected(GiphyDialogFragment.kt:58)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$2.invoke(GiphyDialogFragment.kt:483)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$2.invoke(GiphyDialogFragment.kt:58)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView$onItemSelectedListener$1.invoke(SmartGridRecyclerView.kt:125)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView$onItemSelectedListener$1.invoke(SmartGridRecyclerView.kt:33)
        at com.giphy.sdk.ui.universallist.SmartGridAdapter$onCreateViewHolder$1.onClick(SmartGridAdapter.kt:49)
        at android.view.View.performClick(View.java:7281)
        at android.view.View.performClickInternal(View.java:7255)
        at android.view.View.access$3600(View.java:828)
        at android.view.View$PerformClick.run(View.java:27925)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
`

**Comment by ALexanderLonsky** [comment]
Hey @ow-ro, thanks for flagging this.
We are updating `Exoplayer` to `v2.16.0` as we already have [this request](https://github.com/Giphy/giphy-react-native-sdk/issues/48)
It'll be included in the next release.

You'll need to update it too because it has [breaking changes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2160-2021-11-04)

**Comment by ALexanderLonsky** [comment]
SDK [v2.1.13](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.13) released

**Comment by ow-ro** [comment]
Hi @ALexanderLonsky - after updating to the most recent ExoPlayer release (2.18.1), we are seeing a similar issue, again only affecting clips. Hoping Giphy's exoplayer dependency could be updated again?

Thanks

`2022-08-12 11:15:27.429 3511-3511/com.wemesh.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wemesh.android, PID: 3511
    java.lang.NoSuchMethodError: No virtual method buildUponParameters()Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector$ParametersBuilder; in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~4fxGDyKXyZnp_0hswIMv1w==/com.wemesh.android-yyJfSg3-imXpdn4sD1d69g==/base.apk!classes18.dex)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.loadMedia(GPHVideoPlayer.kt:253)
        at com.giphy.sdk.ui.views.GPHVideoPlayer.loadMedia$default(GPHVideoPlayer.kt:211)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.showVideoAttributionScreen(GiphyDialogFragment.kt:1403)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onGifSelected(GiphyDialogFragment.kt:1129)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.access$onGifSelected(GiphyDialogFragment.kt:58)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$2.invoke(GiphyDialogFragment.kt:483)
        at com.giphy.sdk.ui.views.GiphyDialogFragment$setupGifsRecycler$2.invoke(GiphyDialogFragment.kt:58)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView$onItemSelectedListener$1.invoke(SmartGridRecyclerView.kt:126)
        at com.giphy.sdk.ui.universallist.SmartGridRecyclerView$onItemSelectedListener$1.invoke(SmartGridRecyclerView.kt:34)
        at com.giphy.sdk.ui.universallist.SmartGridAdapter$onCreateViewHolder$1.onClick(SmartGridAdapter.kt:49)
        at android.view.View.performClick(View.java:7520)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

**Comment by ALexanderLonsky** [comment]
Hi @ow-ro,
We have many issues reported due to Exoplayer versioning conflicts.
That's why we decided to move the Exoplayer out of the SDK in the next release.
It'll be a breaking change, and I'll provide details on how to use the new solution. 
I'll keep you in the loop.

**Comment by ALexanderLonsky** [comment]
Hi @ow-ro,

I pushed a new version:

```
implementation "com.giphy.sdk:ui:2.2.0-rc-1"

// You must add Exoplayer dependency to your project:
implementation("com.google.android.exoplayer:exoplayer-core:2.18.1")
implementation("com.google.android.exoplayer:exoplayer-ui:2.18.1")
```

It's a staging version and requires to add:

```
allprojects {
    repositories {
        maven("https://oss.sonatype.org/content/repositories/staging")
        mavenCentral()
    }
}

```

To play clips, the SDK requires providing a `GPHAbstractVideoPlayer` implementation.
I prepared an implementation based on the `ExoPlayer` 2.18.1 version (find it attached):
 - `VideoPlayerExoPlayer2181Impl`

```
 val dialog = GiphyDialogFragment.newInstance(
    settings.copy(selectedContentType = contentType),
    videoPlayer = { playerView, repeatable, showCaptions ->
        VideoPlayerExoPlayer2181Impl(playerView, repeatable, showCaptions)
    }
 )
```

It's required to initialize the `VideoCache`(find it attached) too, you can do it right before `Giphy.configure`:

```
VideoCache.initialize(this, 100 * 1024 * 1024)
Giphy.configure(this, YOUR_API_KEY, true)
```

Please let me know if that works for you.

[VideoPlayerImpl+VideoCache.zip](https://github.com/Giphy/giphy-android-sdk/files/9351172/VideoPlayerImpl%2BVideoCache.zip)

**Comment by ALexanderLonsky** [comment]
@ow-ro 
We removed the ExoPlayer dependency as of version [2.2.0](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.2.0)

This is a breaking change, please follow the updated [clips documentation](https://github.com/Giphy/giphy-android-sdk/blob/main/clips.md#using-clips-in-sdk-v220-or-above).
