### ISSUE TITLE
setMediaWithId throws ConcurrentModificationException

### ISSUE THREAD

**Issue by powerworr** [Giphy/giphy-android-sdk#52]
Replacing `itemView.gifView.setMedia(message.media)` with `itemView.gifView.setMediaWithId(message.media.id)`
and ending https://giphy.com/gifs/southparkgifs-l2Sqj9ZOg8wAvW0Xm few times and scrolling results in this crash:
```2020-05-19 16:15:48.102 16217-16217/com.giphy.sdk.uidemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.giphy.sdk.uidemo, PID: 16217
    java.util.ConcurrentModificationException
        at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:806)
        at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839)
        at com.facebook.datasource.RetainingDataSourceSupplier.replaceSupplier(RetainingDataSourceSupplier.java:37)
        at com.giphy.sdk.ui.views.GifView.replaceImage(Unknown Source:44)
        at com.giphy.sdk.ui.views.GifView.loadCurrentStep(Unknown Source:83)
        at com.giphy.sdk.ui.views.GifView.loadMedia(Unknown Source:84)
        at com.giphy.sdk.ui.views.GifView.access$loadMedia(Unknown Source:0)
        at com.giphy.sdk.ui.views.GifView$media$1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by powerworr** [comment]
Seems that the gif is only 1 frame and maybe that's the cause

**Comment by ALexanderLonsky** [comment]
It's not crashing for me in the latest SDK [version](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.2).
The problem must have been related to [Fresco](https://github.com/facebook/fresco), which we have updated recently.
